export const popularCategories = [
   "Electronics",
   "Fashion (Men's)",
   "Fashion (Women's)",
   "Fashion (Kids)",
   "Home & Furniture",
   "Beauty & Personal Care",
   "Books & Stationery",
   "Sports & Outdoors",
   "Health & Wellness",
   "Appliances",
   "Toys & Games",
   "Automotive & Tools",
   "Jewelry & Accessories",
   "Groceries & Gourmet Foods",
   "Pet Supplies",
   "Musical Instruments",
];